# Generated by Django 3.2.2 on 2021-06-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=30)),
                ('n_bi', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(auto_now=True)),
                ('n_contato', models.CharField(max_length=13)),
                ('n_contato_alternativo', models.CharField(max_length=13)),
                ('nome_pai', models.CharField(max_length=50)),
                ('nome_mae', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=50)),
                ('naturalidade', models.CharField(max_length=30)),
                ('provincia', models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bie', 'Bie'), ('Cabinda', 'Cabinda'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Luanda', 'Luanda'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire'), ('Outra', 'Outra (Estrangeira)')], default='Luanda', max_length=20)),
                ('escola', models.CharField(help_text='O nome da escola que deseja ingressar.', max_length=30)),
                ('ano_lectivo', models.CharField(default=2022, help_text='O ano lectivo que deseja iniciar.', max_length=4)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
