# Generated by Django 3.2.2 on 2021-06-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nacionalidade',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='n_bi',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
